[versions]

groovy = "4.0.22"
jackson = "<jackson-resolve>"
opensesame = "0.5.13"

mdg = "2.0.0-beta.28"

[libraries]

groovy_core = { module = "org.apache.groovy:groovy", version.ref = "groovy" }
groovy_contracts = { module = "org.apache.groovy:groovy-contracts", version.ref = "groovy" }
groovy_datetime = { module = "org.apache.groovy:groovy-datetime", version.ref = "groovy" }
groovy_nio = { module = "org.apache.groovy:groovy-nio", version.ref = "groovy" }
groovy_macro_core = { module = "org.apache.groovy:groovy-macro", version.ref = "groovy" }
groovy_macro_library = { module = "org.apache.groovy:groovy-macro-library", version.ref = "groovy" }
groovy_templates = { module = "org.apache.groovy:groovy-templates", version.ref = "groovy" }
groovy_typecheckers = { module = "org.apache.groovy:groovy-typecheckers", version.ref = "groovy" }
groovy_dateutil = { module = "org.apache.groovy:groovy-dateutil", version.ref = "groovy" }
groovy_ginq = { module = "org.apache.groovy:groovy-ginq", version.ref = "groovy" }
groovy_toml = { module = "org.apache.groovy:groovy-toml", version.ref = "groovy" }
groovy_json = { module = "org.apache.groovy:groovy-json", version.ref = "groovy" }
groovy_xml = { module = "org.apache.groovy:groovy-xml", version.ref = "groovy" }

jackson_core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jackson" }
jackson_annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson_databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson_dataformat_toml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-toml", version.ref = "jackson" }

opensesame_groovy = { module = "dev.lukebemish.opensesame:opensesame-groovy", version.ref = "opensesame" }
opensesame_compile = { module = "dev.lukebemish.opensesame:opensesame-compile", version.ref = "opensesame" }
opensesame_core = { module = "dev.lukebemish.opensesame:opensesame-core", version.ref = "opensesame" }

[plugins]

mdg = {id = "org.groovymc.modsdotgroovy", version.ref = "mdg"}
nexuspublish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
